# Generated by Django 3.2.25 on 2026-02-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Kod produktu')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('unit', models.CharField(choices=[('szt.', 'Sztuka'), ('kg', 'Kilogram'), ('m', 'Metr'), ('m2', 'Metr kwadratowy'), ('m3', 'Metr sześcienny'), ('l', 'Litr'), ('godz.', 'Godzina'), ('usł.', 'Usługa')], default='szt.', max_length=10, verbose_name='Jednostka')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena netto')),
                ('tax_rate', models.IntegerField(choices=[(23, '23%'), (8, '8%'), (5, '5%'), (0, '0%'), (-1, 'zw.')], default=23, verbose_name='Stawka VAT')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produkt/Usługa',
                'verbose_name_plural': 'Produkty/Usługi',
                'ordering': ['name'],
            },
        ),
    ]
