# Generated by Django 3.2.25 on 2026-02-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('nip', models.CharField(blank=True, max_length=15, verbose_name='NIP')),
                ('ulica', models.CharField(blank=True, max_length=255, verbose_name='Ulica')),
                ('miasto', models.CharField(blank=True, max_length=100, verbose_name='Miasto')),
                ('kod_pocztowy', models.CharField(blank=True, max_length=10, verbose_name='Kod pocztowy')),
                ('kraj', models.CharField(default='Polska', max_length=100, verbose_name='Kraj')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('notatki', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kontrahent',
                'verbose_name_plural': 'Kontrahenci',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_nazwa', models.CharField(blank=True, max_length=255, verbose_name='Nazwa firmy')),
                ('firma_nip', models.CharField(blank=True, max_length=15, verbose_name='NIP firmy')),
                ('ksef_token', models.TextField(blank=True, verbose_name='Token KSeF')),
                ('ksef_environment', models.CharField(choices=[('production', 'Produkcja'), ('test', 'Test'), ('demo', 'Demo')], default='test', max_length=20, verbose_name='Środowisko KSeF')),
                ('auto_fetch_ksef', models.BooleanField(default=False, verbose_name='Automatyczne pobieranie z KSeF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ustawienia',
                'verbose_name_plural': 'Ustawienia',
            },
        ),
    ]
