# Generated by Django 3.2.25 on 2026-02-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=100, verbose_name='Numer faktury')),
                ('data', models.DateField(verbose_name='Data faktury')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kwota brutto')),
                ('dostawca', models.CharField(max_length=255, verbose_name='Dostawca')),
                ('termin_platnosci', models.DateField(verbose_name='Termin płatności')),
                ('status', models.CharField(choices=[('niezaplacona', 'Niezapłacona'), ('zaplacona', 'Zapłacona')], default='niezaplacona', max_length=20, verbose_name='Status')),
                ('ksef_numer', models.CharField(blank=True, max_length=100, verbose_name='Numer KSeF')),
                ('ksef_xml', models.TextField(blank=True, verbose_name='XML KSeF')),
                ('notatki', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kontrahent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktury', to='customers.contractor', verbose_name='Kontrahent')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
